### ISSUE TITLE
Input not recognized in the Ledger

### ISSUE THREAD

**Issue by darosior** [revault/liana#133]
When signing a transaction the Ledger says that input aren't recognized. We must be missing a field to set in the PSBT.

**Comment by edouardparis** [comment]
> the warning is because the non-witness-utxo is missing
in segwitv0, the app checks the prevout transaction to make sure about the amount (like for legacy transactions)
that's because there's a bug in segwit where in some cases you could trick the user into spending more money than they think

From Salvatore

**Comment by darosior** [comment]
Alright so it's on me to add this field on the daemon. Assigning myself.
