### ISSUE TITLE
Don't allow duplicate keys

### ISSUE THREAD

**Issue by darosior** [revault/liana#149]
While it's not technically an issue with our single keys template, it is invalid Miniscript. We shouldn't allow that.

**Comment by edouardparis** [comment]
I can prevent it at the installer level. We can forbid keys with same master fingerprint to avoid user to enter two keys derived from the same seed (Or maybe it is too much :stop_sign: ).

**Comment by darosior** [comment]
No it's too much, the idea is just that no two same keys (like raw, actual, public keys) must be part of the same Miniscript.

(It's because a signature for a public key at a given place is also valid for the same public key at another spot.)
------- Original Message -------
