### ISSUE TITLE
GUI: change is incorrectly displayed

### ISSUE THREAD

**Issue by darosior** [revault/liana#200]
From @kloaec:
> Why do i have -0,00438 when i'm actually spending 0.003 (see spend flow video from before)

(see https://github.com/revault/liana/issues/199 for the spend flow mentioned)

![image](https://user-images.githubusercontent.com/22457751/206679504-793ec968-72e4-43fb-bead-3af56bdcfa9d.png)

**Comment by darosior** [comment]
cc @kloaec: i'm not entirely sure of what is the issue here.

**Comment by edouardparis** [comment]
I believe it is all about confusion because of the wrong event selection
