### ISSUE TITLE
GUI: :hourglass: inconsistencies between screens.

### ISSUE THREAD

**Issue by kloaec** [revault/liana#232]
Consistency is important, especially as we use concepts new to users.
The Hourglass :hourglass: icon is sometime displayed, sometimes not. In this case it displays in Coins, but not in Send when a UTXO isn't confirmed.
 
![Screenshot from 2022-12-15 11-44-16](https://user-images.githubusercontent.com/15522963/207862464-b942e9a0-c474-4b75-aa6b-d5b41aa201e7.png)
![Screenshot from 2022-12-15 11-42-33](https://user-images.githubusercontent.com/15522963/207862467-a1d5e373-3cc5-4b01-ae53-da1f4cfc5668.png)

**Comment by darosior** [comment]
The hourglass should always be displayed, with the maximum timelock value for unconfirmed transaction. I'd say it's rather urgent since it is confusing and related to the very new concept introduced in this wallet: timelocks.

**Comment by edouardparis** [comment]
Maybe unconfirmed coins should not appear in the coins selection list of the spend creation process ? what do you think ?

**Comment by darosior** [comment]
It would prevent CPFP. Let's keep them but with an "unconfirmed" label.
------- Original Message -------
