### ISSUE TITLE
GUI?: Bug - hardware is connected but not found after locking/unlocking it

### ISSUE THREAD

**Issue by kloaec** [revault/liana#238]
Trying to find the exact issue and reproduce it, will add in comments when i figure out wtf.

![Screenshot from 2022-12-15 15-00-42](https://user-images.githubusercontent.com/15522963/207909946-1bbd55e1-51c1-4ea8-a256-b1fce9093a76.png)

**Comment by kloaec** [comment]
Definitely Liana related: just restarting Liana-gui, not touching Core nor Specter did fix the issue.

**Comment by kloaec** [comment]
Reproduced:
- hardware connected
- liana detects it
- disconnect hardware
- liana doesn't detect it (normal)
- reconnect hardware
- liana still cannot detect it (not normal)

Rebooting Liana fixes the issue. See video below.
[Screencast from 2022-12-15 15-13-43.webm](https://user-images.githubusercontent.com/15522963/207912218-1747e798-f4c4-4aea-aed2-aa3ab3aced9e.webm)

**Comment by darosior** [comment]
Ouch. Indeed this is very suboptimal. Let's see if we can fix this in the first release.

**Comment by mariabmont** [comment]
[Screencast from 2022-12-16 14-43-01.webm](https://user-images.githubusercontent.com/118536288/208135297-74a4f78b-7d28-4d84-bfdc-a017f3d232de.webm)
It actually works when there is already one HW connected!!
