### ISSUE TITLE
UI / UX review of the GUI for the first version

### ISSUE THREAD

**Issue by darosior** [revault/liana#50]
Before releasing the first version of the software, we need to make a reasonable effort to have a good UX in the GUI. This can be split-off into multiple stages:
1. Inform the development of the GUI. This can for instance take the form of a Bitcoin designer review club.
2. Feature freeze for the first version.
3. First pass at a UI / UX review from our end.
4. Second pass with someone who doesn't know well the product, and is ideally well versed in design and user interfaces.

This issue is an umbrella to centralize the discussion around improving the GUI for the first release of the software. Discussions on specific technicalities can go into their own issue and be linked from there. Discussions on what isn't prioritized for the first version should go in their own issues / another umbrella issues.
Let's discuss everything else here.

**Comment by darosior** [comment]
I did a first pass. Here is a paste of my notes:

## Installer

Can we set a title and an icon to the software? Currently it's labeled "unknown" with a default
image.


When choosing the network, change the labels to:
- Bitcoin mainnet
- Bitcoin testnet
- Bitcoin signet
- Bitcoin regtest


"Create a new descriptor" ..... "or import it" (in small characters) is unclear. What about choosing
between at the same time as the network between:
- Create a new wallet
- Import an existing descriptor

And then show either the creation or the import screen accordingly.


On error creating the descriptor it's not clear that we need to hoover in order to have the reason
for the error. Maybe have a "click for details" button?


On the "register descriptor" screen we can continue without registering the descriptor. We should
probably issue a big warning as if they go on they won't be able to retry without wiping the data
directory and won't be able to sign without manually registering the descriptor on the signing
device.
Also, do we check if the descriptor is *already* registered? We should support that.


The connection to bitcoind screen we pre-filled defaults is great. :)


I had an error finalizing the install. I went back to the first screen. Now i can't move forward
anymore. :sob: :sob:
I need to wipe the data directory and try again.


You should check the network of the xpubs. You should probably do it when importing it from the
signing device then you should call `check()` on minisafed's Config to sanity check it before trying
to start the daemon.


You should probably wipe the data directory if you encounter an error when starting the daemon.
Maybe make it optional, like having a confirmation dialog.


## Wallet GUI

We should define a color scheme IMO.


When creating a new Spend transaction without any coin, i get a "total amount must be superior to X"
error after setting the recipient addresses. It should be something like "no coin available to fund
the transaction" instead.


On the homepage i have a "See more" button that does nothing when i click on it. Even now that i
have some (unconfirmed) coins.


I don't think the icon for the coin should be that. :)


When selecting coins maybe change the message from a "total amount must be superior to X" warning to
a "Please select more than X BTC worth of coins".
We could create a good first issue to update that dynamically.


When creating a Spend i was asked the feerate *after* selecting the coins... What if i have a super
high feerate? And how did you compute how much i needed in the previous screen then?
Ok, obviously if i choose too high of a feerate it fails. The two screen should be swapped and the
necessary amount computed based on the chosen feerate.


Ok, now on to the "Spend transaction details" screen. First information, and in bold is how much is
going out of the wallet. And how much of that is in miner fee. That's good.
Then i feel like there is too much stuff on this screen. Hmm to start the "save the transaction"
tile is way too large (label is top left corner and the button bottom right corner). Actually, do we
need the user to perform an action to save the transaction? We should probably just save it and
remove this whole tile. They can always delete it. And if they created it in the first place, it's
probably to store it. How things stand they could make a mistake and have to do the whole process
again..
The structure of the transaction should probably be hidden in some kind of drop down. Like
"Transaction details".
Also, there should be larger margin between the tiles i feel, to outline the 3 different sections.


The wrong output is detected as change.


Once i've manually saved the transaction, the tile is replaced with "Select hardware wallet to sign
with". But i didn't ask to sign it? Should we hide it? Not a big deal, it can stay as such.


If i click sign and then cancel on the Specter i can't try again, the button is greyed out. I need
to close the screen and get back to try again.


## Second round of GUI review

If i stop the GUI after having finalized the installation and then restart, i'm back to the
installer. It should detect that there is a testnet wallet and ask me if i want to use that instead
of giving me the installer. Better yet, drop me on the GUI for the testnet wallet and give me an
option to launch the installer for another network somewhere in the settings?


Random thought: we should probably have a different color for test networks than for mainnet.


nit: you can't get a new address immediately on the receive screen. You have to quit the screen and
come back to have the next one.


When creating a Spend and entering the amount the focus is left as soon as you start typing the 0
(because of the "Please enter a correct amount" event). Same when the amount then becomes valid.
The focus should stay on the input.


The "coins" tab lists all spent and unspent transaction outputs to our descriptor. In general "coin"
is understood as being a UTxO. It should not list the spent coins. Maybe there could be a toggle to
list them, but not by default IMO.


When creating a Spend the GUI lets me input twice the same address. Worse, it is then going to
forget one of the outputs, apparently. (That must be because it's input in a mapping.)


In "Choose coins", if i go back to the previous screen and set a smaller amount and come back it
stays on the warning/error, i need to unselect then re-select a coin for it to show me the "next"
button.


I created a Spend and somehow the value that move was "-0 BTC". I went back and got back to the tx
details screen and now it's the right value. It seems it was just transient.

**Comment by darosior** [comment]
Next Thursday we'll have some friends giving feedback to @edouardparis on a preview of the GUI. Let's centralize the notes there.

**Comment by darosior** [comment]
- [ ] In addition to my points on the wallet creation / recovery above, you should remove the "heir" lingo: just use "recovery"
- [ ] nit: in the installer, test the connection to bitcoind when configuring it
- [ ] Have the derivation index along with the address in the receiving screen

**Comment by kloaec** [comment]
Testing descriptor backup: I think yes. As I suggested today we may want to also have some kind of test for each key at the end, but that's for later.

Regarding the "Heir" wording, i'm not sure yet how to address this, especially when we will have multiple keys/locktimes. "Recovery" is good as it's generalist, but maybe not clear for people. I suppose we should have a dropdown or tag for each key, for example:

Main key: BC1xxxxxxxxxxxx
Timelock: 14400 blocks

**| Back up key |**     BC1xxxxxxxxxxxxxx

Timelock: 288000 blocks

**| Inheritance key |** / Alice Key:     BC1xxxxxxxxxxxxxx

**Comment by darosior** [comment]
Alright i went through the items in the two lists above. I've created issues for what's left. I don't think there is anything pressing anymore for v0. Well done @edouardparis!
