### ISSUE TITLE
At what derivation should the GUI installer query the key from a signing device?

### ISSUE THREAD

**Issue by darosior** [revault/liana#87]
We need to query from the signing device some xpubs at a specific derivation index, to be used in the descriptor registered in `minisafed`. We'd like to use the same derivation path for all devices. Ledger only allows to sanely query the xpubs from paths that were standardized by BIPs which give an implicit meaning that the key will be used in a specific script (BIP-44 and friends if i'm remembering correctly).

However, i had figured that using a derivation that was already standardized previously could be a source of confusion for the user. We'd query the key for a path with an implicit meaning, and actually not use it in a corresponding Script type.

I now think this isn't actually an issue. There is nowhere the derivation path would be backed up and the user would recover from this. Even in the legacy recovery process, it was the other way around: select the script ("address") type and the software will know from what derivation index to derive keys from for the rescan. Furthermore, we already require the descriptor for recovery. The derivation path used in this descriptor cannot become a source of confusion for the user.

Another consideration that [was brought up by Salvatore Ingala](https://gnusha.org/miniscript/) is about reusing public keys. It's possible we use the derivation path that other software would use let's say for P2WPKH. If someone uses the same signing device on the two software the same public keys (but not addresses obviously) would be used twice onchain.
I think it's not crucial to address, as we can't prevent it: the user could also just use our software twice. But if we can do something like use a different derivation index somewhere in the path (like the "account" thing), let's do it.

My suggestion is therefore:
1. Pick any standard derivation path (for instance the one used for P2WPKH?), and use it for all signing devices
2. Make a best effort at using a different "account" that other software would otherwise use, or even let the user pick one in the installer

**Comment by darosior** [comment]
@edouardparis @kloaec we discussed that together. Do you have any objection or further thoughts on this topic?

**Comment by bigspider** [comment]
> We need to query from the signing device some xpubs at a specific derivation index, to be used in the descriptor registered in `minisafed`. We'd like to use the same derivation path for all devices. Ledger only allows to sanely query the xpubs from paths that were standardized by BIPs which give an implicit meaning that the key will be used in a specific script (BIP-44 and friends if i'm remembering correctly).

The only difference for unusual paths is that the xpub can't be exported silently, user confirmation is required.
It's easy to change that to whitelists some new paths, if needed.

> Another consideration that [was brought up by Salvatore Ingala](https://gnusha.org/miniscript/) is about reusing public keys. It's possible we use the derivation path that other software would use let's say for P2WPKH. If someone uses the same signing device on the two software the same public keys (but not addresses obviously) would be used twice onchain. I think it's not crucial to address, as we can't prevent it: the user could also just use our software twice. But if we can do something like use a different derivation index somewhere in the path (like the "account" thing), let's do it.
> 
> My suggestion is therefore:
> 
> 1. Pick any standard derivation path (for instance the one used for P2WPKH?), and use it for all signing devices
> 2. Make a best effort at using a different "account" that other software would otherwise use, or even let the user pick one in the installer

IMHO standard single-sig paths should be avoided.

Unless a new standard is suggested, using one of the standard BIP-48 paths would be a better option, imho.
BIP-48 paths are standard (and can already be exported silently from Ledger's app), but for them at least the accidental key reuse issue is less important (it was already a problem and software wallets UX should do their best effort to avoid key reuse).
Wallets using standard single-sig paths, on the contrary, don't put _any_ effort into avoiding such key reuse.

**Comment by darosior** [comment]
Alright, so @edouardparis let's use `m/48'/0'/0'/2'`. That's BIP48's P2WSH and is whitelisted by Ledger.

**Comment by edouardparis** [comment]
Because the path is whitelisted, should I remove the verification step on the ledger device too ? Ledger does not require it to retrieve xpub but maybe it is good that user verify that we are not messing with him

**Comment by darosior** [comment]
I don't think we should have it. But it's not your call to remove or add the verification, is it? In any case if the verification isn't triggered by the firmware but the untrusted host it would just give a false sense of security.
------- Original Message -------

**Comment by darosior** [comment]
Done in #152.
